#!/bin/bash

# Check if an argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <component-name>"
  exit 1
fi

COMPONENT_NAME="$1"
COMPONENT_DIR="$COMPONENT_NAME"

mkdir -p "$COMPONENT_DIR"
touch "$COMPONENT_DIR/$COMPONENT_NAME.tsx"
echo "created server component file"
touch "$COMPONENT_DIR/${COMPONENT_NAME}Client.tsx"
echo "created client component file"
touch "$COMPONENT_DIR/$COMPONENT_NAME.module.css"
echo "Created module.css file"
touch "$COMPONENT_DIR/$COMPONENT_NAME.story.tsx"
echo "Created the story file"


