#!/bin/bash

echo "available commands:

"
for file in ~/myshell/rojtxt/*; do
    if [ -f "$file" ] && [[ ! "$file" =~ \.(txt|md|csv)$ ]]; then
        echo "$(basename "$file")"
    fi
done | sort

echo "			"

echo "			"
