#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $0 <source directory>"
  exit 1
fi

source_directory="$1"

if [ ! -d "$source_directory" ]; then
  echo "Error: '$source_directory' is not a valid directory."
  exit 1
fi

txt_files=("$source_directory"/*)
if [ ! -e "${txt_files[0]}" ]; then
  echo "No markdown files found in '$source_directory'."
  exit 1
fi

cat "$source_directory"/* > "$source_directory/combined.txt"
echo "Combined text files into '$source_directory/combined.txt'"
